name: style_cli
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  args: ^2.3.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
