name: style_cli
description: A sample command-line application.
version: 0.0.1+1
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style_cli/
repository: https://github.com/Mehmetyaz/style

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  style: "style_cli"

dependencies:
  args: ^2.3.0
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.19.3
