name: style_object_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.0-106.0.dev <3.0.0'


dependencies:
  build: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
