name: style_object
description: Style object encodinf and decoding. More fast and space saver.
version: 0.0.1
homepage: https://github.com/styledart/style/tree/main/packages/object/style_object

environment:
  sdk: '>=2.17.0 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
