name: style_dart
description: A Backend framework for Dart. Style is a modular,easy-to-understand framework and it have flutter style syntax.
version: 1.0.2+8
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style/
repository: https://github.com/Mehmetyaz/style
publish_to: none


environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  #args: ^2.3.1
  queue: ^3.1.0+1
  json_schema2: ^2.0.2
  style_cron_job: ^1.0.4+2
  vm_service: ^8.3.0
  meta: ^1.8.0

  style_random: ^0.0.1+1
  style_query:
    path: ../style_query


dev_dependencies:
  style_cli:
    path: ../style_cli
  cryptography: ^2.0.5
  lints: ^2.0.0
  test: ^1.21.1
  style_test: ^1.0.0+2